### ISSUE TITLE
Handle unknown block types more gracefully

### ISSUE THREAD

**Issue by barbogast** [sanity-io/block-content-to-hyperscript#17]
At the moment the `BlockSerializer` [throws an error](https://github.com/sanity-io/block-content-to-hyperscript/blob/c8c18eb3adc3ca67daba80ad822a2eb21a2f6a3c/src/serializers.js#L13) for unknown block types. Could the renderer just render nothing, or an error string, and emit a warning instead of throwing an error?

We use different serializers (react + react-native) for the same content, and we have several custom blocks. This means that it is a real risks for the serializers to get out of sync with the block content, and the result would be an ugly crash of the application.

Another case: We render block content in a mobile app. Even if the serializers get updated properly, a lot of users will not update the app immediately. This means that all old versions of the app would crash once a new block element is used in content that is also loaded by old apps.

**Comment by barbogast** [comment]
The configuration could offer to pass a `errorSerializer`. This would be a function that is called with an error object for all errors happening during serialization, and would be expected to return a renderable element.

We would also emit an error report to Sentry in case of an error, which could also be handled in the `errorSerializer`.

**Comment by barbogast** [comment]
Hi, I just realised that #13 does exactly what we would need. Would it possible to merge the PR?

**Comment by balazsorban44** [comment]
@barbogast it just got merged 🎉

**Comment by robations** [comment]
> @barbogast it just got merged 🎉

Should this issue be closed?

**Comment by barbogast** [comment]
I guess so, yeah. Closing...
